### ISSUE TITLE
Create initial application folder structure

### ISSUE THREAD

**Issue by ms0uto** [eemakim/Pokedex#1]
We want to create a clean basic working vanilla React application to start things off.
For this purpose we have the following options:

- Either use [create react app](https://create-react-app.dev/docs/getting-started).
- create our app from a new file and use react depencies through html script tags. (not recommended at all)
- or a third way and most recommended for production use would be to use a [react framework](https://react.dev/learn/start-a-new-react-project)

In this very first MVP application we want to have something minimalistic without compromising utility so we are going to utilize the first method. In a future version (when we have more features and needs) we can upgrade to something like Nextjs.

To close this issue we need:
- [x] to use <s>[create react app](https://create-react-app.dev/docs/getting-started) to scaffold our basic project folder.</s>  [vite](https://vitejs.dev/guide/)  to create our basic project folder
- [x] to create a branch, commit our changes locally after we tested them, and then innitiate a pull request.
- [x] to merge our pull request when its state changes to approved (remember to target the dev branch)

**Remember** to use clean commit messages as for [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) guidelines.
Regarding branches, there are many ways to go about it but for simplicity and for the sake of consistency we are going to use the following way. When we start working on a new issue, we click on **create a branch** on the right side of the github issue view as the following picture shows:

![Image](https://github.com/eemakim/Pokedex/assets/39985547/65d1f879-b3b1-45aa-a099-be8127a85dc6)

This way we don't have to think about branch names. More important, this creates the branch on the remote first so when it comes to pushing the branch we don't have to set upstream.

After checking the option **checkout locally** we just copy the commands that github gives us and start working on our issue.

**Comment by eemakim** [comment]
1. Instead of create react app we have decided to utilise the tool [vite](https://vitejs.dev/guide/) to build the application.
2. New branch created (1-create-initial-application-folder-structure)
3. Pull request created
